"""Generate fix suggestion based on finding and rules."""
import json
import os
import argparse

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--finding", default="finding.json")
    parser.add_argument("--rules", default="auditor/rules/blockchain-audit-rules.txt")
    parser.add_argument("--output", default="FIX_SUGGESTION.md")
    args = parser.parse_args()
    
    if not os.path.exists(args.finding):
        print(f"Finding file not found: {args.finding}")
        return
    
    with open(args.finding, "r") as f:
        finding = json.load(f)
    
    rule_id = finding.get("rule_id", "unknown")
    file_path = finding.get("file", "unknown")
    repo_url = finding.get("repo_url", "unknown")
    repo_name = finding.get("repo_name", "unknown")
    severity = finding.get("severity", "unknown")
    fix_guidance = finding.get("fix_guidance", "No guidance available")
    
    suggestion = "## Fix Suggestion: " + rule_id + "\n\n"
    suggestion += "**Target:** [" + repo_name + "](" + repo_url + ")\n"
    suggestion += "**Rule:** " + rule_id + " - " + finding.get("rule_name", "") + "\n"
    suggestion += "**Severity:** " + severity + "\n"
    suggestion += "**Affected File:** `" + file_path + "`\n\n"
    suggestion += "### Problem\n\n"
    suggestion += "The audit found a potential issue matching rule `" + rule_id + "` in the target repository.\n\n"
    suggestion += "### Recommended Fix\n\n" + fix_guidance + "\n\n"
    suggestion += "### Steps to Apply\n\n"
    suggestion += "1. Review the affected file: `" + file_path + "`\n"
    suggestion += "2. Apply the fix as described above\n"
    suggestion += "3. Run existing tests to verify no regressions\n"
    suggestion += "4. Add tests for the fix if applicable\n\n"
    suggestion += "---\n"
    suggestion += "*Generated by [blockchain-auditor](https://github.com/shunfeng8421/blockchain-auditor) bot*\n"
    
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(suggestion)
    
    print(f"Fix suggestion written to {args.output}")

if __name__ == "__main__":
    main()